# start of pandas

In [1]:
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.2-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Requirement already satisfied: numpy>=1.26.0 in ./venv/lib/python3.13/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in ./venv/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 2.7 MB/s  0:00:04 eta 0:00:01
Installing collected packages: pandas
Successfully installed pandas-3.0.2

In [4]:
import pandas as pd
a=[12,34,523,45432,3454,3234,43]
nga=pd.Series(a)
print(nga)

0       12
1       34
2      523
3    45432
4     3454
5     3234
6       43
dtype: int64

In [11]:
data={
    "day1":390,
    "day2":240
}
nga=pd.Series(data)
print(nga)

day1    390
day2    240
dtype: int64

In [27]:
data={
    "Employee name":["Balen","Nawaraj","Raju","Sacchu","Nirajan"],
    "Salary":[20000,2000000,23456,23453,1111111111],
    "degsination":["Dev","Manager","mistri","don","manager"],
}
d=pd.DataFrame(data)
# print("this is the data printed after the data frame\n",d)
d.head()
# print("this is the data printed by indexing the thing\n",d.loc[1])
# print("this is the data printed by indexing the thing",d[1]) this is not useable it shows the error stuff

  Employee name      Salary degsination
0         Balen       20000         Dev
1       Nawaraj     2000000     Manager
2          Raju       23456      mistri
3        Sacchu       23453         don
4       Nirajan  1111111111     manager

In [ ]:
d=pd.read_csv("customers-100.csv")
d.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,8/24/2020,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,4/23/2021,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,-1199,(496)978-3969x58947,beckycarr@hogan.com,3/25/2020,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,6/2/2020,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,4/17/2021,https://goodwin-ingram.com/

In [15]:
d.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Index              100 non-null    int64
 1   Customer Id        100 non-null    str
 2   First Name         100 non-null    str
 3   Last Name          100 non-null    str
 4   Company            100 non-null    str
 5   City               100 non-null    str
 6   Country            100 non-null    str
 7   Phone 1            100 non-null    str
 8   Phone 2            100 non-null    str
 9   Email              100 non-null    str
 10  Subscription Date  100 non-null    str
 11  Website            100 non-null    str
dtypes: int64(1), str(11)
memory usage: 9.5 KB

In [19]:
d.describe()

            Index
count  100.000000
mean    50.500000
std     29.011492
min      1.000000
25%     25.750000
50%     50.500000
75%     75.250000
max    100.000000

In [5]:
d=pd.read_csv("Mobile_data.csv")
d.head()

,Unnamed: 0,brand_name,model_name,os,popularity,best_price,lowest_price,highest_price,sellers_amount,screen_size,memory_size,battery_size,release_date
0,0,ALCATEL,1 1/8GB Bluish Black (5033D-2JALUAA),Android,422,1690,1529.0,1819.0,36,5.00,8.0,2000.0,20-Oct
1,1,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,323,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
2,2,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,299,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
3,3,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,287,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
4,4,Nokia,1.3 1/16GB Charcoal,Android,1047,1999,NaN,NaN,10,5.71,16.0,3000.0,20-Apr

In [21]:
d.info()

<class 'pandas.DataFrame'>
RangeIndex: 1224 entries, 0 to 1223
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      1224 non-null   int64
 1   brand_name      1224 non-null   str
 2   model_name      1224 non-null   str
 3   os              1027 non-null   str
 4   popularity      1224 non-null   int64
 5   best_price      1224 non-null   int64
 6   lowest_price    964 non-null    float64
 7   highest_price   964 non-null    float64
 8   sellers_amount  1224 non-null   int64
 9   screen_size     1222 non-null   float64
 10  memory_size     1112 non-null   float64
 11  battery_size    1214 non-null   float64
 12  release_date    1224 non-null   str
dtypes: float64(5), int64(4), str(4)
memory usage: 124.4 KB

In [ ]:
d.drop(columns="Unnamed: 0")
d.head()

,Unnamed: 0,brand_name,model_name,os,popularity,best_price,lowest_price,highest_price,sellers_amount,screen_size,memory_size,battery_size,release_date
0,0,ALCATEL,1 1/8GB Bluish Black (5033D-2JALUAA),Android,422,1690,1529.0,1819.0,36,5.00,8.0,2000.0,20-Oct
1,1,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,323,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
2,2,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,299,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
3,3,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,287,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
4,4,Nokia,1.3 1/16GB Charcoal,Android,1047,1999,NaN,NaN,10,5.71,16.0,3000.0,20-Apr

In [12]:
# d.drop(columns="Unnamed: 0",inplace=True)
d.head()

,brand_name,model_name,os,popularity,best_price,lowest_price,highest_price,sellers_amount,screen_size,memory_size,battery_size,release_date
0,ALCATEL,1 1/8GB Bluish Black (5033D-2JALUAA),Android,422,1690,1529.0,1819.0,36,5.00,8.0,2000.0,20-Oct
1,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,323,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
2,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,299,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
3,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,287,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
4,Nokia,1.3 1/16GB Charcoal,Android,1047,1999,NaN,NaN,10,5.71,16.0,3000.0,20-Apr

In [13]:
d["brand_name"].unique()

<StringArray>
[     'ALCATEL',        'Nokia',        'Honor',        'Meizu',
       'realme',      'OnePlus',       'Archos',      'Ulefone',
          'AGM',         'OPPO',        'Astro',       'Rezone',
    'Blackview',       'Bravis',          'NUU',       'Lenovo',
      'UMIDIGI',    'Assistant',    'Crosscall',        'Sharp',
         'ERGO',        'Tecno',          'CAT',       'DOOGEE',
       'Xiaomi',          'ZTE',      'Oukitel',        'Cubot',
       'S-TELL', 'Sigma mobile',      'Coolpad',       'Bluboo',
           'LG',     'Motorola',      'Philips',           '2E',
          'Fly',      'Samsung',    'Prestigio',      'myPhone',
   'BlackBerry',      'KENEKSI',       'Maxcom',       'HUAWEI',
       'Vernee',      'General',       'Globex',      'Smartex',
       'Google',         'ASUS',         'Land',        'MAFAM',
        'Jinga',     'Vodafone',    'Microsoft',     'iOutdoor',
     'Elephone',          'HTC',        'Viaan',         'vivo',
         'Sony',       'LEAGOO',         'Nomi',        'Apple']
Length: 64, dtype: str

In [ ]:
d["os"].unique() #shows unique value

<StringArray>
['Android', nan, 'iOS', 'OxygenOS', 'WindowsPhone', 'EMUI', 'KAIOS']
Length: 7, dtype: str

In [17]:
d["os"].nunique()   # number of unique values

6

In [18]:
d["os"].value_counts()   # count each unique value

os
Android         915
iOS             103
OxygenOS          3
WindowsPhone      3
EMUI              2
KAIOS             1
Name: count, dtype: int64

In [20]:
d.loc[d["brand_name"]=="vivo"] #it help us to search the data according to the name

,brand_name,model_name,os,popularity,best_price,lowest_price,highest_price,sellers_amount,screen_size,memory_size,battery_size,release_date
932,vivo,V20 8/128GB Midnight Jazz,Android,894,11632,10420.0,11999.0,26,6.44,128.0,4000.0,20-Oct
933,vivo,V20 8/128GB Sunset Melody,Android,935,11360,10499.0,11999.0,9,6.44,128.0,4000.0,20-Oct
934,vivo,V20 SE 8/128GB Gravity Black,Android,684,8762,7869.0,8999.0,9,6.44,128.0,4100.0,20-Oct
1008,vivo,X50 8/128GB Frost Blue,Android,829,15507,13849.0,17289.0,24,6.56,128.0,4315.0,20-Jul
1009,vivo,X50 8/128GB Graze Black,Android,892,15505,13849.0,17289.0,25,6.56,128.0,4315.0,20-Jul
1012,vivo,X50 Pro 8/256GB Alpha Grey,Android,981,24519,22099.0,26879.0,14,6.56,256.0,4315.0,20-Jul
1054,vivo,Y11 3/32GB Agate Red,Android,388,3497,NaN,NaN,1,6.35,32.0,5000.0,19-Dec
1055,vivo,Y15 4/64GB Aqua Blue,Android,627,4249,3960.0,4915.0,16,6.35,64.0,5000.0,19-Jul
1056,vivo,Y15 4/64GB Aqua Blue,Android,623,4249,3960.0,4915.0,16,6.35,64.0,5000.0,19-Jul
1057,vivo,Y15 4/64GB Burgundy Red,Android,573,4356,4145.0,4499.0,6,6.35,64.0,5000.0,19-Jul
1058,vivo,Y19 4/128GB Black,Android,739,4998,4997.0,4999.0,2,6.53,128.0,5000.0,19-Dec
1059,vivo,Y1S 2/32GB Black,Android,680,3117,2849.0,3729.0,43,6.22,32.0,4030.0,20-Jul
1060,vivo,Y1S 2/32GB Blue,Android,574,3080,2850.0,3209.0,47,6.22,32.0,4030.0,20-Jul
1061,vivo,Y20 4/64GB Nebula Blue,Android,810,4732,4299.0,4999.0,40,6.51,64.0,5000.0,20-Oct
1062,vivo,Y20 4/64GB Obsidian Black,Android,928,4752,4299.0,5296.0,36,6.51,64.0,5000.0,20-Oct
1063,vivo,Y30 4/64GB Black,Android,587,4481,4399.0,4499.0,7,6.47,64.0,5000.0,20-Jul
1064,vivo,Y30 4/64GB Blue,Android,896,4467,4349.0,4499.0,8,6.47,64.0,5000.0,20-Jul

In [21]:
d["os"].shape            # size of column

(1224,)